# Generated by Django 2.0.3 on 2018-04-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_friends_current_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.FileField(null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
